artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1aocl_FVCPUWUbfZ_au9cTXht5h-9HwK3/view?usp=sharing
  data_dir_name: data22

train_config:
  train_data: artifacts\data_ingestion\data22\ddata.csv
  test_data: artifacts\data_ingestion\data22\ddata.csv
  sep: ";"
  valid_pecent: 0.2
  
model_config:
  n_estimators: 100
  model_save: artifacts\models\model.pkl

mlflow:
  MLFLOW_TRACKING_URI: https://dagshub.com/Phuocphenikaa/mlflow-repo.mlflow 
  MLFLOW_TRACKING_USERNAME: Phuocphenikaa
  MLFLOW_TRACKING_PASSWORD: 0745776f6660d4ffc979b4764460215371d8e8c9   




