artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1aocl_FVCPUWUbfZ_au9cTXht5h-9HwK3/view?usp=sharing
  data_dir_name: data22

train_config:
  data_file: artifacts\data_ingestion\data22\ddata.csv
  valid_pecent: 0.2

test:
  data_file: 
  


